/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_stu_mgp_BussinessCardRecognition_ImageTool */

#ifndef _Included_com_stu_mgp_BussinessCardRecognition_ImageTool
#define _Included_com_stu_mgp_BussinessCardRecognition_ImageTool
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_stu_mgp_BussinessCardRecognition_ImageTool
 * Method:    RectifyCard
 * Signature: (JJJJJ)V
 */
JNIEXPORT void JNICALL Java_com_stu_mgp_BussinessCardRecognition_ImageTool_RectifyCard
  (JNIEnv *, jclass, jlong, jlong, jlong, jlong, jlong, jlong, jlong, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
